name: CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      # Uncomment this line to enable task distribution
      # --stop-agents-after="e2e-ci"
      - run: npx nx start-ci-run --distribute-on="6 linux-medium-js"
        env:
          NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      #  name: Install Dependencies
      # - run: npm install --legacy-peer-deps

      - run: npm ci --legacy-peer-deps


      - run: npx cypress install
      - uses: nrwl/nx-set-shas@v4

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      - run: npx nx-cloud record -- echo Hello World
    #  - name: Cache Nx
      - uses: actions/cache@v3
        with:
          path: .nx/cache
          key: ${{ runner.os }}-nx-${{ github.sha }}

      # When you enable task distribution, run the e2e-ci task instead of e2e
      # --base flag to determine changes against your main branch
      - run: npx nx affected -t lint test build e2e --base=origin/master --head=HEAD --parallel --maxParallel=6
      # Nx Cloud recommends fixes for failures to help you get CI green faster. Learn more: https://nx.dev/ci/features/self-healing-ci
      - run: npx nx fix-ci
        if: always()
